version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        networks:
            - frontend
        volumes:
            - ${PROJECT_PATH}:/var/www/html
            - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
            - ./nginx/logs:/var/log/nginx/
        depends_on:
            - app

    app:
        build: ./php
        networks:
            - backend
            - frontend
        volumes:
            - ${PROJECT_PATH}:/var/www/html
        depends_on:
            - mysql

    mysql:
        container_name: mysql_db
        image: mysql:5.7.22
        ports:
          - "3306:3306"
        volumes:
          - .docker/dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - PMA_HOST=mysql
        networks:
          - backend

networks:
    backend:
    frontend:
